### PR TITLE
Devtool

### PR DESCRIPTION
**Pull request by KamilPiekutowski**

### CODE REVIEW

**Comment by hallard** [comment]
Thanks for contributing, but I noticed you removed my examples, any reason?

**Comment by KamilPiekutowski** [comment]
Sorry, I made that pull request by mistake.
I am working on Yocto project, where I will be providing specific apps that
would take advantage of this library, thus I removed
the examples.

However I can create a public recipe for your project in the near future.

Best Regards,
Kamil Piekutowski

**Comment by hallard** [comment]
Kamil, 

Got it, no problem, I leave it open in case in interest someone.

**Comment by KamilPiekutowski** [comment]
Thank you Charles.

**Comment by KamilPiekutowski** [comment]
Charles, did you test this library on 64-bit raspbian? 
In order to work on my custom yocto image I hade to  disable  ( CONFIG_STRICT_DEVMEM=n ) variable in the  u-boot.
Let me know if you have any problems on 64 kernel. It work fine on mine now.

Best Regards!

**Pull request closed without merging**
